### ISSUE TITLE
nil pointer dereference

### ISSUE THREAD

**Issue by mikehelmick** [google/exposure-notifications-server#886]
Stack trace

2020/08/18 22:55:56 http: panic serving 169.254.8.129:56282: runtime error: invalid memory address or nil pointer dereference goroutine 76 [running]: net/http.(*conn).serve.func1(0xc0005ec140) net/http/server.go:1800 +0x139 panic(0x1409520, 0x24d39e0) runtime/panic.go:975 +0x3e3 github.com/google/exposure-notifications-server/internal/publish/database.(*PublishDB).InsertAndReviseExposures.func1(0x19b9fe0, 0xc000402120, 0xc00063a4e0, 0x163ef35) github.com/google/exposure-notifications-server/internal/publish/database/exposure.go:408 +0x64f github.com/google/exposure-notifications-server/internal/database.(*DB).InTx(0xc000422198, 0x19a4020, 0xc00063a4e0, 0x163ef35, 0xe, 0xc00044f240, 0x0, 0x0) github.com/google/exposure-notifications-server/internal/database/database.go:54 +0x2ab github.com/google/exposure-notifications-server/internal/publish/database.(*PublishDB).InsertAndReviseExposures(0xc000422218, 0x19a4020, 0xc00063a4e0, 0xc00057e820, 0x13, 0x13, 0x0, 0xc000544600, 0xbfc734ff268190e9, 0x29755fa5, ...) github.com/google/exposure-notifications-server/internal/publish/database/exposure.go:374 +0x146 github.com/google/exposure-notifications-server/internal/publish.(*PublishHandler).process(0xc00057d320, 0x19a4020, 0xc00063a240, 0xc00017ed20, 0xc00044f810, 0x0, 0x0, 0x0, 0x0, 0x0) github.com/google/exposure-notifications-server/internal/publish/publish.go:285 +0xbd6 github.com/google/exposure-notifications-server/internal/publish.(*PublishHandler).handleRequest(0xc00057d320, 0x19917e0, 0xc0004fd2a0, 0xc0004b2b00, 0x0, 0x0, 0x0, 0x0, 0x0) github.com/google/exposure-notifications-server/internal/publish/publish_v1.go:54 +0x456 github.com/google/exposure-notifications-server/internal/publish.(*PublishHandler).Handle.func1(0x19917e0, 0xc0004fd2a0, 0xc0004b2b00) github.com/google/exposure-notifications-server/internal/publish/publish_v1.go:61 +0x68 net/http.HandlerFunc.ServeHTTP(0xc0003dc8e0, 0x19917e0, 0xc0004fd2a0, 0xc0004b2b00) net/http/server.go:2041 +0x44 github.com/mikehelmick/go-chaff.(*Tracker).HandleTrack.func1(0x1994560, 0xc0006db590, 0xc0004b2b00) github.com/mikehelmick/go-chaff@v0.3.0/tracker.go:212 +0x10a net/http.HandlerFunc.ServeHTTP(0xc000565710, 0x1994560, 0xc0006db590, 0xc0004b2b00) net/http/server.go:2041 +0x44 net/http.(*ServeMux).ServeHTTP(0xc000425000, 0x1994560, 0xc0006db590, 0xc0004b2b00) net/http/server.go:2416 +0x1a5 go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc0003a5e00, 0x1994560, 0xc0006db590, 0xc000439000) go.opencensus.io@v0.22.4/plugin/ochttp/server.go:92 +0x27e net/http.serverHandler.ServeHTTP(0xc00039fc00, 0x1993020, 0xc00060c380, 0xc000439000) net/http/server.go:2836 +0xa3 net/http.(*conn).serve(0xc0005ec140, 0x19a3f60, 0xc0003cc880) net/http/server.go:1924 +0x86c created by net/http.(*Server).Serve net/http/server.go:2962 +0x35c

**Comment by mikehelmick** [comment]
This can only happen if revision tokens are being bypassed.
